backend:
  name: github
  repo: hendrikmolder/molder2
  # branch: master
  # squash_merges: true

media_library:
 name: uploadcare
 config:
   publicKey: 29907a7620b6f1832daf

collections:
  - name: "pages"
    label: "Pages"
    folder: src/content/pages
    create: true
    fields:
      - { name: title, label: Name }
      - { name: slug, label: Slug, required: false }
      - { name: showTitle, label: Show Title, widget: boolean, required: false, default: true }
      - { name: type, widget: hidden, default: page }
      - { name: date, label: Date, widget: date, format: YYYY-MM-DDTHHZ }
      - { name: author, label: Author}
      - { name: body, label: Body, widget: markdown }
  - name: "posts"
    label: "Blog"
    folder: src/content/blog
    create: true
    fields:
      - { name: title, label: Title }
      - { name: type, widget: hidden, default: blog }
      - { name: date, label: Date, widget: date, format: YYYY-MM-DDTHHZ }
      - { name: author, label: Author, default: "Hendrik Mölder"}
      - { name: body, label: Body, widget: markdown }
